version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=pmdevops
      - JWT_SECRET=superSecret
      - ENCRYPTION_KEY=12345678901234567890123456789012
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
