name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Auth Service
      - name: Auth Service - Install & Test
        run: |
          cd auth-service
          npm install
          npm test

      - name: Auth Service - Docker Build
        run: |
          cd auth-service
          docker build -t myuser/auth-service:${{ github.sha }} .

      # Vault Service
      - name: Vault Service - Install & Test
        run: |
          cd vault-service
          npm install
          npm test
      
      - name: Vault Service - Docker Build
        run: |
          cd vault-service
          docker build -t myuser/vault-service:${{ github.sha }} .
      
      # Utility Service
      - name: Utility Service - Install & Test
        run: |
          cd utility-service
          npm install
          npm test -- --passWithNoTests  # Allow Jest to pass even if no tests exist

      - name: Utility Service - Docker Build
        run: |
          cd utility-service
          docker build -t myuser/utility-service:${{ github.sha }} .
